### ISSUE TITLE
Search among multiple files

### ISSUE THREAD

**Issue by mathieumg** [sindresorhus/find-up#11]
Are there plans to add support (or be open to PRs that do) finding one of multiple files before walking up the file tree and/or function-based search? (À la `Array.prototype.find`)

Say if I want to look for "fileA" and if not found look for "fileB" and then, if not found, go up one directory and start again, I could do the following:

```js
findUp(["fileA.png", "fileB.png"]).then(filepath => {
    console.log(filepath);
});
```

Simple example using the `find` approach, but it would be the most flexible:

```js
findUp(filename => filename === "unicorn.png").then(filepath => {
    console.log(filepath);
});
```

Thank you!

**Comment by sholladay** [comment]
Seems like a valid need, but there's some trickiness here.

With the array example, I'm not sure it's clear that the semantics are _some_ and not _every_. And if this were to be implemented, I feel like people will end up asking for both.

Your second example using a filename `find` function doesn't seem like a good fit here, or at least the machinery would be very different. What's nice about `find-up` is that it simply does [this](https://github.com/sindresorhus/find-up/blob/95f370bb723f2fb3881c141640c745cb2d80f8ff/index.js#L15)... 

```
pathExists(fp)
```

... and keeps walking up.

In order to provide you with filenames, `find-up` would have to do a directory listing at every level of the tree via `fs.readdir` and either provide you with that list (for you to iterate through yourself) or iterate through it for you and call you on each entry, as in your example.

Either way we're probably talking multiple orders of magnitude more disk I/O here, so we'd want to make the `pathExists` checks concurrent where possible. For this, we'd need something like [p-any](https://github.com/sindresorhus/p-any) that returns a filepath as soon as we can confirm one exists or null if we eventually determine that none of them do. Oh but `pAny` is actually a race - is it important that we respect the order of your array in the case where more than one of those paths exists at a given depth?

These are some of the immediate issues that come to mind.

**Comment by mathieumg** [comment]
> With the array example, I'm not sure it's clear that the semantics are some and not every. And if this were to be implemented, I feel like people will end up asking for both.

An array implies ordering, but I agree that people *might* want the other. What do you suggest? Perhaps a different data structure for when ordering doesn't matter (such as a `Set` or an object literal where only keys are looked at) or always an array and an option in the second parameter that indicates whether it's "one of" or "all of"?

> In order to provide you with filenames, find-up would have to do a directory listing at every level of the tree via fs.readdir and either provide you with that list (for you to iterate through yourself) or iterate through it for you and call you on each entry, as in your example.

> we're talking multiple orders of magnitude more disk I/O

Agreed. I don't really need that level of flexibility, was just thinking about the most flexible API and hadn't considered the implementation cost yet. I would be fine sticking to a "suggestion list".

> is it important that we respect the order of your array in the case where more than one of those paths exists at a given depth

It is. The parameter would be a list of acceptable files, at every level, in order of preference.

**Comment by sholladay** [comment]
Cool, thanks for the details. I would suggest making a prototype. Might not be worth it until Sindre chimes in, though.

**Comment by mathieumg** [comment]
Will look into it tomorrow, shouldn't be very long or complex. Sorry for the delay and thanks for the quick feedback!

**Comment by mathieumg** [comment]
See https://github.com/mathieumg/find-up/commit/28579ae9d0a663b994aff8f996be1222e08b73bf

I only implemented the "search in order" approach for now to give an idea. Sadly, I didn't find something (even in https://github.com/sindresorhus/promise-fun) along the line of `[/* Array of Promises */].find(firstFoundValue => /* ... */)` that respects the order but remains optimistic (unlike `Promise.race()` which ignores the order and `Promise.all()` which isn't optimistic) so I implemented a basic version, it obviously doesn't belong in this module once we're done.

**Comment by mathieumg** [comment]
ping @sholladay

**Comment by sholladay** [comment]
Thanks for working on this. Makes it a lot easier to discuss and weigh the pros and cons. Feel free to open a PR to make it even easier to give feedback.

Is the repo where you want to use this open source? Mind sharing more about the use case?

I'm also curious about the kinds of files you are searching for. Often `find-up` is used for configuration files. What leads you to use this pattern?

The implementation seems pretty good. Happy to see it's relatively simple. Kudos for using TDD! 

> I didn't find something ... that respects the order but remains optimistic

Indeed, this seems like an excellent promise utility.

**Comment by mathieumg** [comment]
> Feel free to open a PR to make it even easier to give feedback.

I'll separate the "promise find" utility to its own module, and then proceed to open the PR shortly.

> Is the repo where you want to use this open source? Mind sharing more about the use case?

Yes it is. Basically, I want to implement `package.json5` support to https://github.com/tjunnone/npm-check-updates. (Already approved by the maintainers) See https://github.com/tjunnone/npm-check-updates/blob/a47a0cffc47ab2549c6561f9a2cc2a7588cb82d7/lib/npm-check-updates.js#L379

I think this answers the other questions too. :grin:

**Comment by sindresorhus** [comment]
> I only implemented the "search in order" approach for now to give an idea. Sadly, I didn't find something (even in https://github.com/sindresorhus/promise-fun) along the line of [/* Array of Promises */].find(firstFoundValue => /* ... */)

I have lots of `p-*` modules I unfortunately haven't had the time to write docs for and publish yet. I just published a module to simplify this: [`locate-path`](https://github.com/sindresorhus/locate-path) (uses [`p-locate`](https://github.com/sindresorhus/p-locate) underneath).

**Comment by mathieumg** [comment]
Cool! Updated my branch by leveraging that module and opened a PR as suggested above.
