### ISSUE TITLE
Unclear return type in docs

### ISSUE THREAD

**Issue by HarrySarson** [sindresorhus/find-up#13]
For https://github.com/sindresorhus/find-up#findupfilename-options.

>### findUp(filename, [options])
> Returns a `Promise` for the filepath or `null`.

This confused me when I first read it as it suggests that `findUp` returns null when a file cannot be found. I looked at the source and it (obviously) returns a promise that resolves to null. I was being thick but could this be reworded to help out future (also thick) users.

e.g.
> Returns a `Promise` that evaluates either to the filepath or to `null` if the file cannot be found.

**Comment by sholladay** [comment]
> it suggests that findUp returns null when a file cannot be found

I take it you mean literal `null` not wrapped in a `Promise`. That would be the only incorrect assumption here.

Promise-based APIs always wrap all of their return values in a `Promise`. This is a de facto convention that comes with the territory. Even errors are generally rejected promises. The only one exception being [programmer errors](http://www.2ality.com/2016/03/promise-rejections-vs-exceptions.html), but some people reject instead of `throw` even for these.

All of that said, it could be improved. I will take care of this later tonight.

**Comment by HarrySarson** [comment]
Yeah, it does make sense/is correct - just might catch someone new to promises out.
