### ISSUE TITLE
Issue with nyc

### ISSUE THREAD

**Issue by suculent** [sindresorhus/find-up#16]
Hi, I'm not really sure whether this is a nyc or find-up issue:

$ nyc
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received [ '.nycrc', '.nycrc.json' ]
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1167:7)
    at join (/usr/local/lib/node_modules/nyc/node_modules/find-up/index.js:11:14)
    at Function.module.exports.sync (/usr/local/lib/node_modules/nyc/node_modules/find-up/index.js:43:12)
    at Object.Config.loadConfig (/usr/local/lib/node_modules/nyc/lib/config-util.js:17:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/nyc/bin/nyc.js:23:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

10:46:09 {master} $ node -v
v8.1.4

**Comment by sholladay** [comment]
I had to do some digging to figure this out, but based on that stack trace it appears you are on an old version of `find-up`. Specifically, version `1.1.2` or earlier. That is the last time `path.join()` [was used on line 11](https://github.com/sindresorhus/find-up/blob/f2d7c1ff74fbac82b2cff038e311ef4b075d9184/index.js#L11).

The error indicates that the `filename` given to `find-up` was an array. But support for that was only added in version `2.1.0`. So you will need to upgrade or fix the implementation in `nyc` (e.g. by calling `find-up` for each individual file instead).

Presumably there was a buggy release of `nyc` that has this problem, which I bet they fixed promptly. So you may be able to simply update to a newer `nyc`. If not, a temporary workaround for you is to `cd /usr/local/lib/node_modules/nyc` and modify its `package.json` so that the version for `find-up` is `^2.1.0` and then reinstall the dependencies with `rm -rf node_modules && npm install` to get the update. Don't worry about the major version bump, the only breaking change was dropping support for old versions of Node and you appear to be on a Node version that we support.

**Comment by suculent** [comment]
Thanks for awesome tip with replacing the dependency version. I was wondering how to do that.

The issue appeared after upgrading both nyc and node so it will probably just take some time to settle.

**Comment by sholladay** [comment]
I found the relevant `nyc` commit that started giving us an array: https://github.com/istanbuljs/nyc/commit/a1a457facd07d94a4387b81c96690d757ecc154c

They did upgrade the `find-up` dependency correctly, whereas my guess was that they forgot to.

I am still inclined to believe, based on your stack trace, that somehow you ended up with an up-to-date `nyc` but an out-of-date `find-up` with incompatible implementations. I'm not sure how that would have happened, but at this point my best guess is some kind of bug in `npm`. Did you by any chance use `npm update` rather than `npm install`?

If I were you, I would go with the nuclear option: `npm cache clean && npm install -g npm && npm install -g nyc`

**Comment by sholladay** [comment]
Closing as I am 99% sure there is nothing we can do about this here. Will reopen if something new comes to light.

Downstream issue: https://github.com/istanbuljs/nyc/issues/631

**Comment by bcoe** [comment]
this is an issue with npm, and will be addressed in upcoming bug fixes.

**Comment by sholladay** [comment]
@bcoe would you mind providing a link to the relevant npm issue?
