### ISSUE TITLE
Find file in several parent directories

### ISSUE THREAD

**Issue by piranna** [sindresorhus/find-up#19]
Instead of stop when a file is found (or got to `root` dir), add an option to continue looking up and return and array with all the parent directories that have a file with the required filename.

**Comment by sholladay** [comment]
You will be able to do this yourself when https://github.com/sindresorhus/find-up/issues/21 is implemented.

Below, I make a list of all parent directories that have a `package.json` child.

```js
const dirsWithPkg = [];
await findUp((dir) => {
    if (path.existsSync(path.join(dir, 'package.json'))) {
        dirs.push(dir);
    }
});
```

I'm going to close this issue since I think #21 will be good enough. It's not the cleanest, purest way for the user, but I doubt @sindresorhus will want to add any extra sugar for this.

Could be a good example to put in the documentation, though!
