### ISSUE TITLE
find-up does not default to .js / .json extension (unlike require)

### ISSUE THREAD

**Issue by danday74** [sindresorhus/find-up#20]
This does not work:

```
let webpackConfigPath = findUp.sync('webpack.config')
// fails (AKA returns null) if a file called webpack.config.js exists in cwd
let webpackConfig = require(webpackConfigPath)
```

Unlike this:

```
let webpackConfig = require('webpack.config')
// works if a file called webpack.config.js exists in cwd
```

To match the behaviour of require, find-up should:

(1) try to find webpack.config
(2) try to find webpack.config.js // adhering to the behaviour of require
(3) try to find webpack.config.json // adhering to the behaviour of require

And should only return null if none of the above are found.

**Comment by sindresorhus** [comment]
`find-up` is not meant to work like `require`. What you want is https://github.com/sindresorhus/resolve-from

**Comment by sholladay** [comment]
To expand on what Sindre said, `require()` is primarily intended to load modules, which inherently must be in a specific format. It happens to also be able to load data for convenience, but its use cases are quite limited and focused, by design.

`findUp()`, on the other hand, is intended to find literally anything. It doesn't parse the file, it doesn't care what format it is in, etc. Its use cases are much broader. If anything, I believe `findUp()` is more commonly used to find data than modules, so if it were to make assumptions about file extensions, I think there's an argument to be made that it should prefer `.json` over `.js`. In practice, that would probably be a bit surprising since people are so accustomed to the order that `require()` uses. But I think it illustrates my point that the overlap in design goals is nearly non-existent, beyond the fact that they both need to find files.

There are other, smaller issues to consider. `require()` is basically a legacy API now. It's still largely being used, but its days are numbered. ES Modules are here and gaining significant traction. The thing about ESM is that we are finally able to design truly cross-platform modules, but browsers do not support extensionless imports because they cannot walk the filesystem. So using an explicit extension is a new best practice for anyone who wants their code to "just work" in both environments. Will that happen in droves? Too early to say, but quite possibly. This whole "guess the extension" concept may be a dying thing.

On top of that, we are talking about a 3x increase in the number of filesystem checks per file argument, per directory in the tree we have to traverse. 4x if we need to support [`.mjs`](https://nodejs.org/api/esm.html#esm_enabling). I'm normally not too concerned about performance, but this could add up. And `findUp()` is used *a lot*. 1.3 million downloads on npm just today. There would be plenty of wasted time looking for `.gitignore.json` and the like. I suppose it could be opt-in, but I doubt many people would use it.

**Comment by danday74** [comment]
@sindresorhus

"find-up is not meant to work like require" ... maybe a bad design decision

"What you want is https://github.com/sindresorhus/resolve-from" ... nope I want find-up

@sholladay

Nice thoughtful feedback many thanks and much appreciated. I personally would expect it to work like require but your arguments against are very good - happy to see this closed due to your reasoning - many thanks for your time

**Comment by sindresorhus** [comment]
> maybe a bad design decision

No, @sholladay just explained why it’s a good design descision.

> nope I want find-up

`resolve-from` does exactly what you requested.

**Comment by sholladay** [comment]
I'm guessing the reason `resolve-from`, on its own, doesn't work for @danday74, is because his code doesn't necessarily know what to use for `fromDir`.

Something like this would generally work by convention, though, since config for tools like webpack is usually stored next to `package.json`.

```js
const pkgDir = require('pkg-dir');
const resolveFrom = require('resolve-from');

const init = async () => {
    const configPath = resolveFrom(await pkgDir(), './webpack.config');
    console.log('config path:', configPath);
};
init();
```
The code above searches upwards for `package.json` and then tries to find the webpack config as a sibling, using the normal `require()` resolution rules.

If that won't work for you because you genuinely need to be able to find the config at any level of the tree regardless of the presence of `package.json`, then you're still in luck! We support an ordered list of multiple filenames to search for. All you have to do is map over your desired extensions, as below.

```js
const findUp = require('pkg-dir');

const init = async () => {
    const needle = 'webpack.config';
    const filenames = Object.keys(require.extensions).map((ext) => {
        return needle + ext;
    });
    const configPath = await findUp(filenames);
    console.log('config path:', configPath);
};
init();
```

This can become even simpler and more robust when https://github.com/sindresorhus/find-up/issues/21 is implemented, because then you'll be able to do per-directory `require()` resolution using `find-up` and `resolve-from` together.

```js
const findUp = require('find-up');
const resolveFrom = require('resolve-from');

const init = async () => {
    const configPath = await findUp((dir) => {
        return resolveFrom(dir, './webpack.config');
    });
    console.log('config path:', configPath);
};
init();
```
