### ISSUE TITLE
script failing on node v8.2.1

### ISSUE THREAD

**Issue by pastelInc** [sindresorhus/find-up#44]
find-up@4.1.0 script is failing using node v8.2.1:

```
/Users/xxx/my-project/node_modules/find-up/index.js:29
		const foundPath = await runMatcher({...options, cwd: directory});
		                                    ^^^

SyntaxError: Unexpected token ...
```

I ran example.js listed in README.md.

**Comment by sholladay** [comment]
Looks like you will need Node 8.6 or higher, as that is the first 8.x version to support object spread, which we are using, hence the SyntaxError.

**Comment by sindresorhus** [comment]
> I will update our package.json to reflect the specific Node version required.

It's expected that user's upgrade patch and minor versions. Discussion: https://github.com/sindresorhus/meta/issues/8

**Comment by pastelInc** [comment]
>I will update our package.json to reflect the specific Node version required.

Thank you. I'm looking forward to it 👍

**Comment by pastelInc** [comment]
>It's expected that user's upgrade patch and minor versions. Discussion: sindresorhus/meta#8

It was a new discovery! Is this the official opinion of npm

**Comment by sholladay** [comment]
I'll leave my thoughts in the discussion linked above. But simply put, I would say `find-up` using new syntax is an _especially_ breaking change (as opposed to just using new APIs), since users cannot polyfill syntax. To me, it's the sort of thing that we should be very explicit about. It may only matter to a small number of users (since patch versions of Node are, in theory, easy to adopt), but it's also a very easy thing for us to document. I don't see many reasons _not_ to update `versions.node` when issues like this are identified.

**Comment by ArunRamachandran** [comment]
I know it's a bit late, but I have faced the same issue recently & managed to resolve it by upgrading the node version to v12.0.0.
